add linux webserver script
slashrelativepath/relativepath-cycle-6 pull request #13
Opened 2023-11-16 23:54 UTC by papaPanda72

2023-11-17 04:52 UTC, stephenlauck requested changes

2023-11-17 04:52 UTC, stephenlauck commented on linux-webserver.sh
> +  sudo apt install -y multipass
Need to use Snap to install multipass, not apt.

https://multipass.run/install

2023-11-18 00:01 UTC, ChrisForti approved these changes

2023-11-18 02:19 UTC, stephenlauck approved these changes

2023-11-21 23:22 UTC, merged