Instruction on how to install poshgit via Chocolatey.
slashrelativepath/relativepath-cycle-6 pull request #8
Opened 2023-11-07 23:16 UTC by zaylon10

2023-11-07 23:17 UTC, thatoldplatitude commented
nit: have branch up to date with main

2023-11-07 23:18 UTC, eld120 approved these changes

2023-11-08 00:43 UTC, stephenlauck requested changes
What if we convert this README to a powershell ps1 that we could just run?

2023-11-15 23:41 UTC, stephenlauck approved these changes
ok to merge just for historical purpose.

2023-11-19 21:29 UTC, eld120 commented on windows-poshgit.ps1
> +  echo "chocolatey already installed"
@zaylon10  let's change the terminal output on line 20 from "chocolatey already installed" to "git already installed"

2023-11-20 00:09 UTC, ChrisForti commented
This not ready for merge, needs to be tested on another windows machine. We were getting intermittent errors, saying that poshgit is not cmdlet function.

2023-11-20 01:05 UTC, stephenlauck approved these changes

2023-11-20 23:30 UTC, merged